vim.g.use_codicons = true
local icons = {
	separators = {
		slant = { left = "", right = "" },
		rounded = { left = "", right = "" },
		arrow = { left = "", right = "" },
		straight = { left = "|", right = "|" },
		bar = { left = "▎", right = "▕" },
		arrow_bracket = { left = "", right = "" },
		rounded_bracket = { left = "", right = "" },
		blank = { left = "", right = "" },
	},
	borders = {
		square = {
			top = "─",
			bottom = "─",
			left = "│",
			right = "│",
			top_left = "┌",
			top_right = "┐",
			bottom_left = "└",
			bottom_right = "┘",
			inter_left = "├",
			inter_right = "┤",
			inter_top = "┬",
			inter_bottom = "┴",
			center = "┼",
		},
		round = {
			top = "─",
			bottom = "─",
			left = "│",
			right = "│",
			top_left = "╭",
			top_right = "╮",
			bottom_left = "╰",
			bottom_right = "╯",
			inter_left = "├",
			inter_right = "┤",
			inter_top = "┬",
			inter_bottom = "┴",
			center = "┼",
		},
		square_thick = {
			top = "━",
			bottom = "━",
			left = "┃",
			right = "┃",
			top_left = "┏",
			top_right = "┓",
			bottom_right = "┛",
			bottom_left = "┗",
			inter_left = "┣",
			inter_right = "┫",
			inter_top = "┳",
			inter_bottom = "┻",
			center = "╋",
		},
		edge = {
			top = "▀",
			bottom = "▄",
			left = "▌",
			right = "▐",
			top_left = "▛",
			top_right = "▜",
			bottom_left = "▙",
			bottom_right = "▟",
			inter_left = "▌",
			inter_right = "▐",
			inter_top = "▀",
			inter_bottom = "▄",
			center = " ",
		},
		edge_thin = {
			top = "▔",
			bottom = "▁",
			left = "▏",
			right = "▕",
			top_left = "🭽",
			top_right = "🭾",
			bottom_left = "🭼",
			bottom_right = "🭿",
			inter_left = "▏",
			inter_right = "▕",
			inter_top = "▔",
			inter_bottom = "▁",
			center = " ",
		},
	},
	kind = {
		Array = " ",
		Boolean = " ",
		Class = " ",
		Color = " ",
		Constant = " ",
		Constructor = " ",
		Enum = " ",
		EnumMember = " ",
		Event = " ",
		Field = " ",
		File = " ",
		Folder = " ",
		Function = "󰊕 ",
		Interface = " ",
		Key = " ",
		Keyword = " ",
		Method = " ",
		Misc = " ",
		Module = " ",
		Namespace = " ",
		Null = " ",
		Number = " ",
		Object = " ",
		Operator = " ",
		Package = " ",
		Property = " ",
		Reference = " ",
		Snippet = " ",
		String = " ",
		Struct = " ",
		Text = " ",
		TypeParameter = " ",
		Unit = " ",
		Value = " ",
		Variable = " ",
	},
	ui = {
		ArrowClosed = "",
		ArrowOpen = "",
		ArrowFillClosed = "",
		ArrowFillOpen = "",
		ArrowNavLeft = " ",
		ArrowNavRight = " ",
		Lock = " ",
		Circle = " ",
		Circle_Empty = " ",
		Dot = "● ",
		Mason = "◍ ",
		Diamond = "◆",
		Close = "",
		NewFile = " ",
		Search = " ",
		FileSearch = "󰱼",
		Multi_Select = " ",
		Caret_Arrow = " ",
		Lightbulb = "",
		Project = " ",
		Session = " ",
		Dashboard = " ",
		History = " ",
		Clock = " ",
		Comment = " ",
		Chat = "󰭹 ",
		Bug = " ",
		Code = " ",
		Telescope = " ",
		Gear = " ",
		Package = " ",
		List = " ",
		BulletList = " ",
		StatusList = "󱖫 ",
		SignIn = " ",
		SignOut = " ",
		Check = " ",
		Fire = " ",
		Note = " ",
		BookMark = " ",
		Book = "",
		Pin = "",
		Pencil = "󰏫 ",
		Question = " ",
		ChevronRight = "",
		Table = "",
		Calendar = "",
		CloudDownload = "",
		Server = " ",
		Stacks = " ",
		Scopes = "",
		Watches = "󰍉 ",
		Term = " ",
		Prompt = "❱",
		Repeat = "󰑖 ",
		Ellipses = "…",
		Tab = " ",
		Space = "󱁐 ",
		House = " ",
		Wand = " ",
		Brain = "",
		Calc = "󰃬 ",
		Tag = " ",
		FoldSuffix = "󰁂 ",
		Undo = "󰕍 ",
		Beaker = " ",
		ArcChart = "󰄦 ",
		Star = " ",
		Block = "█",
		Recording = "󰑋",
	},
	debug = {
		Pause = "",
		Play = "",
		Step_into = "",
		Step_over = "",
		Step_out = "",
		Step_back = "",
		Run_last = "",
		Terminate = "",
		Breakpoint = "󱎕",
		BreakpointCond = "󱍠",
		BreakpointLog = "",
	},
	characters = {
		eol = "↲",
		extends = "›",
		nbsp = "␣",
		precedes = "‹",
		space = "·",
		tab = "|->",
		trail = "×",
		indent = "▎",
		indent_focus = "▎",
		showbreak = "▋",
	},
	diagnostic = {
		error = "󰅙 ",
		warn = " ",
		hint = "󰌵 ",
		info = " ",
		[1] = "󰅙 ",
		[2] = " ",
		[3] = "󰌵 ",
		[4] = " ",
	},
	task = {
		status = {
			FAILURE = "󰅚 ",
			CANCELED = " ",
			SUCCESS = "󰄴 ",
			RUNNING = "󰑮 ",
		},
	},
	testing = {
		covered = "█",
		uncovered = "█",
		partial = "█",
	},
	git = {
		Add = "+",
		Mod = "~",
		Remove = "-",
		Octoface = " ",
		Branch = "",
		Diff = " ",
		-- signs = {
		-- 	add = "│",
		-- 	mod = "│",
		-- 	delete = "╷",
		-- 	top_delete = "╵",
		-- 	change_delete = "┝",
		-- 	untracked = "┆",
		-- 	diff = "╱",
		-- },
		signs = {
			add = "▐",
			mod = "▐",
			delete = "▗",
			top_delete = "▝",
			change_delete = "▜",
			untracked = "┇",
			diff = "╱",
		},
	},
	arrows = {
		left = " ",
		down = " ",
		up = " ",
		right = " ",
	},
	numbers = {
		superscript = {
			[0] = "⁰",
			[1] = "¹",
			[2] = "²",
			[3] = "³",
			[4] = "⁴",
			[5] = "⁵",
			[6] = "⁶",
			[7] = "⁷",
			[8] = "⁸",
			[9] = "⁹",
		},
		subscript = {
			[0] = "₀",
			[1] = "₁",
			[2] = "₂",
			[3] = "₃",
			[4] = "₄",
			[5] = "₅",
			[6] = "₆",
			[7] = "₇",
			[8] = "₈",
			[9] = "₉",
		},
	},
	letters = {
		superscript = {
			a = "ᵃ",
			b = "ᵇ",
			c = "ᶜ",
			d = "ᵈ",
			e = "ᵉ",
			f = "ᶠ",
			g = "ᵍ",
			h = "ʰ",
			i = "ⁱ",
			j = "ʲ",
			k = "ᵏ",
			l = "ˡ",
			m = "ᵐ",
			n = "ⁿ",
			o = "ᵒ",
			p = "ᵖ",
			q = "𐞥",
			r = "ʳ",
			s = "ˢ",
			t = "ᵗ",
			u = "ᵘ",
			v = "ᵛ",
			w = "ʷ",
			x = "ˣ",
			y = "ʸ",
			z = "ᶻ",
		},
	},
}

return icons
